# Generated by Django 5.2.7 on 2025-10-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('suhu', models.FloatField()),
                ('kelembapan', models.FloatField()),
                ('prediksi', models.CharField(max_length=100)),
            ],
        ),
    ]
